@startuml ConceptStates

state ConceptCreated
state ConceptWaitingforDefinition
state ConceptWaitingforClassification
state ConceptWithDefinitions
state ConceptWithJustifications


ConceptCreated: category
ConceptCreated: keyword
ConceptWaitingforDefinition:category
ConceptWaitingforDefinition:keyword
ConceptWaitingforDefinition: DefinitionQuestion open for a limited time
ConceptWaitingforDefinition: AnswersToReview
ConceptWithDefinitions: category
ConceptWithDefinitions: keyword
ConceptWithDefinitions: Real/Fake Definitions
ConceptWithDefinitions: DefinitionQuestion Closed
ConceptWaitingforJustification:  JustificationQuestion open for a limited time
ConceptWaitingforJustification: AnswersToReview

ConceptWithJustifications: category
ConceptWithJustifications: keyword
ConceptWithJustifications: Real/Fake Definitions
ConceptWithJustifications: Real/Fake Justifications
ConceptWithJustifications: JustificationQuestion Closed


[*] --> ConceptCreated : Teacher:createConcept
ConceptCreated --> ConceptWaitingforDefinition : Teacher:OpenDefinitionQuestion
ConceptWaitingforDefinition -> ConceptWaitingforDefinition : Student: AddAnswer
ConceptWaitingforDefinition --> ConceptWithDefinitions : Teacher:ReviewAnswers
ConceptWithDefinitions --> ConceptWaitingforJustification : Teacher: OpenJustificationQuestion
ConceptWaitingforJustification -->ConceptWithJustifications : Teacher : ReviewAnswers
ConceptWaitingforJustification -> ConceptWaitingforJustification : Student: AddAnswer
ConceptCreated -> ConceptWaitingforClassification : Teacher: OpenClassQuestion
ConceptWaitingforClassification -> ConceptWaitingforClassification : Student : AddAnswer
ConceptWaitingforClassification --> ConceptWithClassification : Teacher: ReviewAnswer
'ConceptWithDefinitions -> ConceptWaitingforClassification : Editor: OpenClassQuestion
'ConceptWithJustifications -> ConceptWaitingforClassification : Editor: OpenClassQuestion
@enduml