@startuml ConceptStates

state ConceptCreated
state ConceptWaitingforDefinition
state ConceptWaitingforClassification
state ConceptWithDefinitions
state ConceptWithJustifications


ConceptCreated: category
ConceptCreated: keyword
ConceptWaitingforDefinition:category
ConceptWaitingforDefinition:keyword
ConceptWaitingforDefinition: DefinitionQuestion opened limited time
ConceptWaitingforDefinition: AnswersToReviewDefinition

ConceptWithDefinitions: Real/Fake Definitions
ConceptWithDefinitions: DefinitionQuestion Closed

[*] --> ConceptCreated : Editor:createConcept
ConceptCreated --> ConceptWaitingforDefinition : Editor:OpenDefinitionQuestion
ConceptWaitingforDefinition --> ConceptWithDefinitions : Reviewer:ReviewAnswers
ConceptWithDefinitions --> ConceptWaitingforJustification : Editor: OpenJustificationQuestion
ConceptWaitingforJustification -->ConceptWithJustifications : Reviewer : ReviewAnswers
ConceptCreated -> ConceptWaitingforClassification : Editor: OpenClassQuestion
ConceptWaitingforClassification --> ConceptWithClassification : Reviewer: ReviewAnswer
ConceptWithDefinitions -> ConceptWaitingforClassification : Editor: OpenClassQuestion
ConceptWithJustifications -> ConceptWaitingforClassification : Editor: OpenClassQuestion
@enduml