@startuml OpoTestDomain

class Community {}

class User {
    #role
    #Test composeTest()
}

class Editor {

}

class Reviewer {

}

class Player {

}

enum Category {
    create()
}

enum Subcategory {

}

class Test {
    #List[] questions
}

class Question {
    #creator
    #creationDate
    #reviewer
    #reviewDate

    #statement
    #List[] answers

}
class Answer {
    # isCorrect
}

Community *-- "1..*" User

Editor <|-- User
Reviewer <|-- User
Player <|-- User

User o-- Test

Test *--> "1..*" Question
Question *--> "1..*" Answer

Question *--> Category
Category *-->"0..*" Subcategory




