@startuml ConceptDomainDetail

class Category 

class Concept

class Keyword

class Definition

class RealDefinition

class FakeDefinition

class Justification

class RealJustification

class FakeJustification

class Relation

class Classification

class Composition

class Level

class Primary {
    withKeyword
}

class Secundary {
    withKeyword
    withDefinition
}

class Tertiary {
    withKeyword
    withDefinition
    withJustification
}

class DefinitionQuestion {
    + statement:
     "¿Qué es KEYWORD?"
    + 1 open answer
}

class ReverseDefinitionQuestion {
    + statement:
     "¿Qué es esta REALDEFINITION?"
    + 1 open answer
}

class JustificationQuestion {
    +statement:
"¿La KEYWORD es esta DEFINITION?¿Por qué?"
    + 1 open answer
}

class KeywordNotFakeDefinitionFakeJustQuestion {
    +statement:
"Es cierto que la CLAVE no es FAKEDEFINITION porque
FAKEJUSTIFICACION"
automatic answers
    + 1 correct answer:
"No porque la justificación es falsa"
    + 3 incorrect answer:
"Sí, por FAKEJUSTIFICATION"...
    
}

class ClassQuestion  {
    +statement:
"Dime los distintos tipos de KEYWORD"
    + 1 open answer 
}

class Question 

class Statement

class Answer 

class Correct

class Incorrect

class AnswersToReviewDefinition {
    answers
    addDefinition(keyword)
}

class AnswersToReviewJustification {
    answers
    addJustification(keyword,definition)
}

class AnswerToReviewIncorrectAnswer {
    answers
    addFakeKeyword(AutomaticReverseQuestion)
}

class AnswersToReviewClasses {
    answers
    addClassification(otherConceptKeyword,relation)
}
Category o--"0..n" Category

Category --* Concept
Concept *-- Keyword
Concept o--"0..n" Definition
Definition <|-- RealDefinition
Definition <|-- FakeDefinition

RealDefinition o-- "0..n" Justification
FakeDefinition o-- "0..n" Justification

Justification <|-- RealJustification
Justification <|-- FakeJustification

Concept o-- "0..n" Relation
Relation <|-- Classification
Relation <|-- Composition
Classification *-- "2..n" Concept
Composition *-- "1..n" Concept

Category --* Question

Level <|-- Primary
Level <|-- Secundary
Level <|-- Tertiary
'Level <|-- WithRelations
  'WithRelations <|-- WithComposition
  'WithRelations <|-- WithClassification
 'WithRelations <|-- WithAsociation
 'WithRelations <|-- WithUse
Primary <|-- DefinitionQuestion
 'Primary <.. Keyword
 'DefinitionQuestion --|> Open
 DefinitionQuestion --> AnswersToReviewDefinition
 'AnswersToReview --> RealDefinition
 'AnswersToReview --> FakeDefinition
Secundary <|-- ReverseDefinitionQuestion
ReverseDefinitionQuestion --> AnswerToReviewIncorrectAnswer 
 'Secundary <.. Keyword
 'Secundary <.. Definition
 ' ReverseDefinitionQuestion --|> Open
 ' ReverseDefinitionQuestion --> Relation
 Secundary <|-- JustificationQuestion
  JustificationQuestion --> AnswersToReviewJustification
 ' AdvancedQuestion --> Justification
 
 'Tertiary <.. Keyword
 'Tertiary <.. Definition
 'Tertiary <.. Justification
Tertiary <|-- KeywordNotFakeDefinitionFakeJustQuestion

'WithClassification <|-- ClassQuestion
Primary <|-- ClassQuestion
ClassQuestion --> AnswersToReviewClasses

Answer <|-- Open
Answer <|-- Automatic

Level --* Concept
Level --* Question
Question *--  Statement
Question o--"3" Incorrect
Question o-- Correct
Question *-- Answer
Automatic <|-- Correct
Automatic <|-- Incorrect
@enduml
 









