@startuml OpoTestDomain

class Community

class User

class Teacher

class Student

class Evaluation

class Result

class Category 

class Test 

class Concept {
    - keyword
}

class Question {
    - level
}

class Statement

class Answer 

class Open 

class MultipleChoice

class Option

class Correct

Class Incorrect

class OpenField {
    - isEvaluated
    - isToConcept
}

Class SelectedOption


Community *--"2..n" User
Community o--"0..n" Category

Category o--"0..n" Category : Subcategories

User <|-- Teacher
User <|-- Student

Teacher -->"0..n" Concept
Concept --o Category
Question --o Concept
Concept o-- Definition
Definition o-- Justification
Justification o-- Explication
Concept o-- Relation

Student -->"0..n" Evaluation
Evaluation --> Test
Evaluation --> Result

Teacher ..> Evaluation
'AnswersToReview *--  OpenField
Definition <.. OpenField :isToConcept
Justification <.. OpenField :isToConcept
Relation <.. OpenField :isToConcept

Evaluation <.. OpenField : manual (! isEvaluated)
Evaluation <.. SelectedOption : automatic

Test *--"1..n" Question
Question <|-- MultipleChoice
Question <|-- Open
Question *--   Statement
MultipleChoice *--"2..n" Option
Option <|-- Incorrect
Option <|-- Correct
MultipleChoice *-- Correct
MultipleChoice *--"1..n" Incorrect
MultipleChoice *-- SelectedOption
Open o--"1..n" OpenField
Answer <|-- OpenField
Answer <|-- SelectedOption


@enduml




