@startuml OpoTestDomain

class Community

class User

class Teacher

class Student

class Evaluation

class Category 

class Test 

class AnswersToReview

class Concept {
    keyword
}

class Open 

class Question

class MultipleChoice

class Statement

class Answer 

class Correct

Class Incorrect

Community *-- "2..n" User
Community o-- "0..n" Category

User <|-- Teacher
User <|-- Student

Teacher ..> Category
Teacher ..> Concept
Concept --o Category
Question --o Concept
Concept o-- Definition
Definition o-- Justification
Concept o-- Relation

Student --> "0..n" Evaluation
Evaluation --> Test

Teacher ..> AnswersToReview : Review
AnswersToReview *-- "1..n" Open
Definition <.. AnswersToReview
Justification <.. AnswersToReview
Relation <.. AnswersToReview

'Question <|-- MultipleChoice
'Question <|-- Open
Test *-- "1..n" Question
Question *--   Statement
Question o-- Answer
MultipleChoice *-- Incorrect
MultipleChoice *-- Correct
Answer <|-- Correct
Answer <|-- Incorrect
Answer <|-- Open
Answer <|-- MultipleChoice


Category o--"0..n" Category : Subcategories



@enduml




