	
@startuml OpoTestPlanteamiento
actor Usuario

database Local
App -> API: Authentication Request
API --> App: Authentication Response

App -> API: Collections Request
API <-- App: Collections Response

database OpotestDb

API -> OpotestDb

@enduml