@startuml QuestionStates

state Created
state InProgress
state InReview
state Ready

Created :  Category
Created : Subcategory
Created : Statement
Created : CorrectAnswer

InProgress : +WrongAnswer

InReview : Reviewed

Ready : Available to add to a Test

[*] -> Created : Editor: CreateQuestion
Created -> InProgress : Editor / Editors : AddAnswers
InProgress -> InReview : 4answer ToReview
InReview -> InProgress : Not Approved
InReview -> Ready : Approved


@enduml