@startuml QuestionStates

state Created
state InReview
state Ready

Created :  Category
Created : Statement
Created : CorrectAnswer

InReview : Reviewed

Ready : Available to add to a Test

[*] -> Created : Editor: CreateQuestion
Created -> InReview : 4answer ToReview
InReview -> Created : Not Approved
InReview -> Ready : Approved


@enduml