@startuml QuestionStates

state CategoryCreated
state ConceptCreated
state QuestionCreated
state QuestionInReview
state QuestionReady

CategoryCreated: Hierarchy
ConceptCreated : Category

QuestionCreated :  Category
QuestionCreated : Statement
QuestionCreated : 4Answer

QuestionInReview : Reviewed

QuestionReady : available in Public Test

[*] -> CategoryCreated : Reviewer:createCategory
CategoryCreated -> ConceptCreated : Editor:createConcept
ConceptCreated-> QuestionCreated : Editor:createQuestion
QuestionCreated -> QuestionInReview : Editor: mark ToReview
QuestionInReview -> QuestionCreated : Reviewer: Not Approved
QuestionInReview -> QuestionReady : Reviewer: Approved

@enduml