@startuml useCases_app
left to right direction
actor User
actor Editor
actor Reviewer
usecase "Login" as login
usecase "Register" as register
usecase "Create Question" as createQ
usecase "Import Question" as importQ
usecase "Update Question" as updateQ
usecase "Delete Question" as deleteQ

usecase "Compose Test" as composeT
usecase "Edit Test" as editT
usecase "Delete Test" as deleteT
usecase "Execute Test" as execT

usecase "Edit Category" as editC
usecase "Send To Review Question" as sendQ

usecase "Review Question" as review

Editor --|> User
Reviewer --|> Editor
Executor --|> User

Editor --> createQ
Editor --> importQ
Editor --> updateQ
Editor --> deleteQ
Editor --> sendQ

User --> login
User --> register
User --> composeT
User --> editT
User --> deleteT
Executor --> execT

Editor --> editC

Reviewer --> review

@enduml