@startuml
left to right direction
actor User as u
usecase "Login" as login
usecase "Create Question" as createQ
usecase "Update Question" as updateQ
usecase "Delete Question" as deleteQ

usecase "Compose Test" as composeT
usecase "Edit Test" as editT
usecase "Play Test" as playT

u --> login
u --> createQ
u --> updateQ
u --> deleteQ

u --> composeT
u --> editT
u --> playT


@enduml