@startuml useCases_app
left to right direction
actor User
actor Editor
actor Reviewer
usecase "Login" as login
usecase "Register" as register
usecase "Logout" as logout

usecase "Create Concept" as createConcept
usecase "Select Level" as selectLevel
usecase "Create Open Question" as createQ
usecase "Close Question" as deleteQ

'usecase "Select Categories" as selectCats
usecase "Show stats" as stats
usecase "Execute Test" as execT

usecase "Create Category" as createCat
usecase "Edit Category" as editC
usecase "Mark ToReview Question" as markQ
usecase "** Evaluate" as rejectA
usecase "Review Answers" as reviewQ
usecase "**Save Concept Element" as publishQ


Editor --|> User
Reviewer --|> Editor
Executor --|> User

Editor --> createConcept
Editor --> selectLevel
Editor --> createQ
Editor --> deleteQ
Editor --> markQ

User --> login
User --> register
User --> logout

'Executor --> selectCats
Executor --> stats
Executor --> execT

Reviewer --> createCat
Reviewer --> editC
Reviewer --> reviewQ
    reviewQ ..> rejectA :include
    reviewQ ..> publishQ :include


@enduml